services:
  spark-notebook:
    build: .
    ports:
      - "8888:8888"   # Jupyter
      - "4040:4040"   # Spark UI
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./scripts:/home/jovyan/work/scripts
      - ./data:/home/jovyan/work/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=spark2026
    command: start-notebook.sh --NotebookApp.token='spark2026'
